 version: '3.3'

 services:

   bot:
     container_name: "${BOT_CONTAINER_NAME}"
     build:
       context: .
     command:
       python main.py
     network_mode:
       "host"
     restart: always
     env_file:
       - ".env"
     volumes:
       - .:/src

